<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Prescription - {{ $prescription->patient->name }}</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #333; font-size: 14px; }
        .header { border-bottom: 2px solid #007bff; padding-bottom: 20px; margin-bottom: 30px; }
        .hospital-name { font-size: 24px; font-weight: bold; color: #007bff; margin: 0; }
        .hospital-details { font-size: 12px; color: #777; margin-top: 5px; }
        
        .meta-table { width: 100%; margin-bottom: 30px; }
        .meta-table td { vertical-align: top; }
        .meta-label { font-weight: bold; color: #555; width: 80px; }
        
        .rx-header { font-size: 20px; font-weight: bold; font-style: italic; margin-bottom: 15px; }
        
        .drugs-table { width: 100%; border-collapse: collapse; margin-bottom: 40px; }
        .drugs-table th { background-color: #f8f9fa; text-align: left; padding: 10px; border-bottom: 1px solid #ddd; }
        .drugs-table td { padding: 10px; border-bottom: 1px solid #eee; }
        
        .footer { position: fixed; bottom: 0; left: 0; right: 0; height: 100px; text-align: center; font-size: 12px; color: #aaa; border-top: 1px solid #eee; padding-top: 20px; }
        .signature { text-align: right; margin-top: 50px; margin-right: 20px; }
        .signature-line { border-top: 1px solid #333; width: 200px; display: inline-block; margin-top: 40px; }
    </style>
</head>
<body>
    <div class="header">
        <h1 class="hospital-name">Clinical Pro Hospital</h1>
        <div class="hospital-details">
            123 Alagbaka Estate, Akure, Ondo State<br>
            Phone: +234 800 CLINICAL | Email: help@clinicalpro.com
        </div>
    </div>

    <table class="meta-table">
        <tr>
            <td width="60%">
                <div class="meta-label">PATIENT:</div>
                <strong>{{ $prescription->patient->name ?? 'N/A' }}</strong><br>
                <small>ID: {{ $prescription->patient->user_id ?? 'N/A' }}</small><br>
                <small>Age/Gender: {{ $prescription->patient->age_gender ?? 'N/A' }}</small>
            </td>
            <td width="40%">
                <div class="meta-label">DOCTOR:</div>
                <strong>Dr. {{ $prescription->doctor->name ?? 'N/A' }}</strong><br>
                <small>{{ $prescription->doctor->doctorProfile->specialization ?? 'General Practitioner' }}</small>
                <br><br>
                <div class="meta-label">DATE:</div>
                <strong>{{ $prescription->created_at->format('d M, Y') }}</strong>
            </td>
        </tr>
    </table>

    <div class="rx-header">Rx (Prescription)</div>

    <table class="drugs-table">
        <thead>
            <tr>
                <th>Drug Name</th>
                <th>Dosage</th>
                <th>Type</th>
                <th>Duration</th>
                <th>Use Pattern</th>
                <th>Instructions</th>
            </tr>
        </thead>
        <tbody>
            @foreach($prescription->items as $item)
            <tr>
                <td>
                    <strong>{{ $item->drug->name ?? $item->medication_name ?? 'N/A' }}</strong>
                </td>
                <td>{{ $item->dosage ?? '-' }}</td>
                <td>{{ $item->type ?? '-' }}</td>
                <td>{{ $item->duration ?? '-' }}</td>
                <td>{{ $item->use_pattern ?? '-' }}</td>
                <td>{{ $item->instructions ?? 'As directed' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="signature">
        <span class="signature-line"></span><br>
        <strong>Dr. {{ $prescription->doctor->name ?? 'N/A' }}</strong><br>
        <small>Signature & Stamp</small>
    </div>

    <div class="footer">
        This is a computer-generated document. No signature is required.<br>
        Generated by Clinical Pro System on {{ now()->format('Y-m-d H:i:s') }}
    </div>
</body>
</html>